spring.datasource.url=jdbc:postgresql://localhost:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.type-aliases-package=com.microservicio.authService.Entity
jwt.secret=RenzoIvanMichelle20232027SeguridadExtra!!
mybatis.configuration.map-underscore-to-camel-case=true
server.port=8080