version: '3.9'

services:

  postgres-user-db:
    image: postgres:17
    container_name: postgres-user-db
    restart: always
    environment:
      POSTGRES_DB: sicaeUsuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/sicaeUsuario.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sicaeUsuario"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./authService/authService/
      dockerfile: dockerfile
    container_name: auth-service
    depends_on:
      postgres-user-db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user-db:5432/sicaeUsuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  user-service:
    build:
      context: ./userService/userService/
      dockerfile: dockerfile
    container_name: user-service
    depends_on:
      postgres-user-db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user-db:5432/sicaeUsuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
